include:
  # Metadata shared by many jobs
  - local: .gitlab/rules.yml
  - local: .gitlab/artifacts.yml

  # OS builds
  - local: .gitlab/os-android.yml

stages:
  - Test SDK
  - Build Sample
  - Publish To Maven

############################################## pipeline jobs

buildSample:debug:
  extends:
    - .conf:env
    - .conf:debug
    - .conf:artifacts
    - .conf:runner:tags
    - .conf:rule:default
    - .buildSample:do

publishToMaven:release:
  extends:
    - .conf:env
    - .conf:release
    - .conf:runner:tags
    - .conf:rule:release
    - .publishMaven:do

############################################## Module (SDK) Tests

testSDK:release:
  extends:
    - .conf:release:testSDK
    - .testSDK:do